### ISSUE TITLE
REQ: Matchtag always in countdown centerprint

### ISSUE THREAD

**Issue by blaps** [deurk/ktx#98] opened 2020-04-22 09:21 UTC
Setting a mode (i.e. 1on1) prints "matchtag not set" in console. 
This should be printed on the countdown centerprint aswell, just like when a tag is actually set.

Could tags be extended to accept more than a-z, 0-9 (and plus and minus chars)? Currently they get squished to a underscore:
Input: /1on1 1on1 · final!
Output: /1on1 1on1 _ final_

**Comment by meag** [comment] 2020-12-18 20:14
Closing - this is broadcast to clients in the serverinfo string already, please re-open in ezquake repo

**Comment by meag** [comment] 2020-12-18 20:15
Sorry, re-opening - was intended for https://github.com/deurk/ktx/issues/99

**Comment by tcsabina** [comment] 2021-03-13 18:08
@deurk , @meag ,
Any particular reason why clean_string() is needed? What is happening with a matchtag? Does it go into the demo? What characters do we need to forbid? I see that space is allowed. Why not the exclamation mark?

**Comment by tcsabina** [comment] 2021-03-13 18:12
@blaps ,
Take a look on this:
![ezquake019](https://user-images.githubusercontent.com/17887592/111039741-e974b000-842f-11eb-994e-de64321d1d45.png)

I am not 100% sure that this looks good. What do you think?

**Comment by blaps** [comment] 2021-03-29 10:52
Looks great!

How about changing the text to:
`NO MATCHTAG`

and if it is set, then:
`MATCHTAG DM FINAL`

In the set case, could the "DM FINAL" text be set with a color, to pop? like brown letters.

**Comment by tcsabina** [comment] 2021-04-21 18:40
Implemented in 1.40 (and later)

**Closed by tcsabina** 2021-04-21 18:40 UTC
Labels: enhancement, matches
