### ISSUE TITLE
k_teamoverlay dont work

### ISSUE THREAD

**Issue by mr0wnage** [deurk/ktx#65] opened 2020-01-13 15:33 UTC
teamoverlay turns on every time after a map change

**Comment by VVD** [comment] 2020-02-14 22:16
Why did you closed it?

**Comment by mr0wnage** [comment] 2020-02-14 22:20
in my opinion it works not right
it always reset to 1 after map change, can be fixed by put 'set k_teamoverlay "0"' to  in ktx/configs/usermodes/default.cfg it should work.

**Comment by mushis** [comment] 2020-02-17 09:57
so... put 'set k_teamoverlay "0"' to in ktx/configs/usermodes/default.cfg works?

**Comment by mr0wnage** [comment] 2020-02-17 10:10
yeah it works...
but 'set k_teamoverlay "0"' in ktx.cfg didnt work

it must be installed every time the map starts
this is wrong in my opinion

**Comment by mushis** [comment] 2020-02-17 11:02
well, imo the behavior should be <remember the last setting> until all the settings are reset.

Removing the k_teamoverlay setting in default configs should be enough to do this. but in my tests, it wasn't (tested nquakesv windows). So this should be the issue here.

looking at the code, at this block in commands.c :
`// common settings for all user modes
const char common_um_init[] =`
there's a bunch of settings, including `"k_teamoverlay 1\n"`
which might be the issue here.  So i've tested it, compiled KTX without that line, and everything worked as intended.

![image](https://user-images.githubusercontent.com/3011167/74648110-eba90400-5174-11ea-88ea-846ce9d612e9.png)

So the fix is 2 things:
* change usermodes/default.cfg
* change commands.c

**Comment by VVD** [comment] 2020-02-17 13:23
Keep it on by default in default.cfg, but remove from reset code in commands.c.

**Comment by deurk** [comment] 2020-03-13 07:52
Changed in 2b0681e878ad9b3285994e43f6d399e6bd67d5c9, now reset to 0 by default, unless default.cfg says otherwise, which I think is the intended goal.

**Closed by deurk** 2020-03-13 07:52 UTC

**Comment by mushis** [comment] 2020-03-13 13:28
@deurk the commit link shows weird characters. are you sure its ok and there's no encoding issue?
